# Generated by Django 4.1.1 on 2022-09-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_todolistitem_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolistitem',
            name='value',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
