# Generated by Django 4.1.1 on 2022-09-19 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0005_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='author',
        ),
    ]
